In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,6]])
arr2=np.array([[5,6,7],[6,8,9]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [3 4 6]
 [5 6 7]
 [6 8 9]]


In [24]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,6]])
arr2=np.array([[5,6,7],[6,8,9]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 5 6 7]
 [3 4 6 6 8 9]]


In [25]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.vstack((arr1,arr2))
print(arr)


[[1 2 3]
 [5 6 7]]


In [26]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.hstack((arr1,arr2))
print(arr)


[1 2 3 5 6 7]


In [27]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.stack((arr1,arr2),axis=1)
print(arr)


[[1 5]
 [2 6]
 [3 7]]


In [29]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.dstack((arr1,arr2))
print(arr)


[[[1 5]
  [2 6]
  [3 7]]]


In [33]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarr1=np.array_split(arr1,3)
print(newarr1)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarr1=np.array_split(arr1,4)
print(newarr1)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [35]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[9,7],[7,0],[56,90]])
newarr1=np.array_split(arr1,3)
print(newarr1)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [9, 7]]), array([[ 7,  0],
       [56, 90]])]


In [36]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[9,7],[7,0],[56,90]])
newarr1=np.array_split(arr1,4)
print(newarr1)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [9, 7]]), array([[7, 0]]), array([[56, 90]])]


In [38]:
import numpy as np
array1=np.array([1,34,67])
array2=np.array([90,56,45])
result=np.dot(array1,array2)
print(result)

5009


In [39]:
import numpy as np
array1=np.array([1,34,67])
array2=np.array([90,56,45])
result=np.dot(array1,array2)
result

np.int32(5009)

In [40]:
import numpy as np
array1=np.array([[1,34,67],[78,90,34]])
array2=np.array([[90,56,45],[90,67,56]])
result=np.inner(array1,array2)
result

array([[ 5009,  6120],
       [13590, 14954]])

In [41]:
import numpy as np
array1=np.array([[1,34,67],[78,90,34]])
array2=np.array([[90,56,45],[90,67,56]])
result=np.outer(array1,array2)
result

array([[  90,   56,   45,   90,   67,   56],
       [3060, 1904, 1530, 3060, 2278, 1904],
       [6030, 3752, 3015, 6030, 4489, 3752],
       [7020, 4368, 3510, 7020, 5226, 4368],
       [8100, 5040, 4050, 8100, 6030, 5040],
       [3060, 1904, 1530, 3060, 2278, 1904]])

In [45]:
import numpy as np
array1=np.array([1,34,7])
array2=np.array([0,5,4])
result=np.outer(array1,array2)
result

array([[  0,   5,   4],
       [  0, 170, 136],
       [  0,  35,  28]])

In [46]:
import numpy as np
array1=np.array([1,34,7])
array2=np.array([0,5,4])
result=np.inner(array1,array2)
result

np.int32(198)

In [52]:
import numpy as np
array=np.array([[1,34],[5,4]])
result=np.linalg.det(array)
print(result)

-166.00000000000006


In [53]:
import numpy as np
array=np.array([[1,34],[5,4]])
result=np.linalg.inv(array)
print(result)

[[-0.02409639  0.20481928]
 [ 0.03012048 -0.0060241 ]]
